/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/tfchart.component';
const styles_TFChartComponent:any[] = ['crosshairCanvas[_ngcontent-%COMP%] {\n            cursor: crosshair;\n        }'];
export const RenderType_TFChartComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_TFChartComponent,
  data: {}
}
);
export function View_TFChartComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵqud(201326592,1,{chartContainerRef: 0}),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,[
      [
        1,
        0
      ]
      ,
      [
        'chartContainer',
        1
      ]

    ]
      ,(null as any),1,'div',[[
        'style',
        'height: 100%; width:100%; position: relative'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵted((null as any),['\n      ']))
  ]
  ,(null as any),(null as any));
}
function View_TFChartComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'tfchart',[[
        'style',
        'height: 100%'
      ]
    ],(null as any),(null as any),(null as any),View_TFChartComponent_0,RenderType_TFChartComponent)),
    import0.ɵdid(2121728,(null as any),0,import1.TFChartComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const TFChartComponentNgFactory:import0.ComponentFactory<import1.TFChartComponent> = import0.ɵccf('tfchart',import1.TFChartComponent,View_TFChartComponent_Host_0,{
  period: 'period',
  series: 'series',
  enableDebug: 'enableDebug'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3RvbS9Qcm9qZWN0cy9uZy10ZmNoYXJ0L3NyYy90ZmNoYXJ0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy90b20vUHJvamVjdHMvbmctdGZjaGFydC9zcmMvdGZjaGFydC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy90b20vUHJvamVjdHMvbmctdGZjaGFydC9zcmMvdGZjaGFydC5jb21wb25lbnQudHMuVEZDaGFydENvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvdG9tL1Byb2plY3RzL25nLXRmY2hhcnQvc3JjL3RmY2hhcnQuY29tcG9uZW50LnRzLlRGQ2hhcnRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgPGRpdiAjY2hhcnRDb250YWluZXIgc3R5bGU9XCJoZWlnaHQ6IDEwMCU7IHdpZHRoOjEwMCU7IHBvc2l0aW9uOiByZWxhdGl2ZVwiPlxuICAgICAgICA8L2Rpdj5cbiAgICAgICIsIjx0ZmNoYXJ0PjwvdGZjaGFydD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQ1E7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBMEU7SUFDcEU7Ozs7OztNQ0ZkO1FBQUE7UUFBQTtNQUFBO0lBQUE7Z0JBQUE7Ozs7Ozs7OzsifQ==
